In [194]:
import numpy as np
a = np.array([[5., 10., 2., 1.],
                  [3., 0., 2., 1.],
                  [0.5, 2., 1., 6.]])
b = np.array([[3., 3., 1.],
                  [2., 5. ,3.],
                  [0.1, 20., 2.],
                  [0., 4., 1.]])
c = np.array([[1., 0.5],
                  [4.,3.]])
print(c)
print(a)
print(b)

[[1.  0.5]
 [4.  3. ]]
[[ 5.  10.   2.   1. ]
 [ 3.   0.   2.   1. ]
 [ 0.5  2.   1.   6. ]]
[[ 3.   3.   1. ]
 [ 2.   5.   3. ]
 [ 0.1 20.   2. ]
 [ 0.   4.   1. ]]


In [195]:
def multiply2d(A, B):
    prod = np.array([[0.,0.,0.],
                 [0.,0.,0.],
                [0.,0.,0.]])
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                prod[i, j] += A[i][k] * B[k][j]
    return prod

In [197]:
print('c x c =',multiply2d(c, c))
print('a x b =',multiply2d(a, b))

c x c = [[ 3.  2.  0.]
 [16. 11.  0.]
 [ 0.  0.  0.]]
a x b = [[ 35.2 109.   40. ]
 [  9.2  53.    8. ]
 [  5.6  55.5  14.5]]
